import{createRepository}from'../data/repositories/ApiRepositories.js';import{StudentApp}from'../presentation/student/StudentApp.js';import{InstructorApp}from'../presentation/instructor/InstructorApp.js';import{AdminApp}from'../presentation/admin/AdminApp.js';import{t}from'../infrastructure/i18n/translations.js';
const app=document.getElementById('app');
let repo=null,bootError=null,booting=true;
const lang=()=>localStorage.getItem('aiQuest.language')||'he';
function setDocumentLanguage(l){document.documentElement.lang=l;document.documentElement.dir='rtl'}
function errorMessage(err){return String(err?.message||err||'unknown_error').slice(0,180)}
function renderFatal(err){const l=lang();setDocumentLanguage(l);app.className='app-shell route-student';app.innerHTML=`<nav class="tabs app-tabs"><a href="#student" class="active">${t(l,'student')}</a><a href="#instructor">${t(l,'instructor')}</a><a href="#admin">${t(l,'admin')}</a></nav><div id="screen"><section class="card connection-error"><h1>${t(l,'connectionProblem')}</h1><p>${t(l,'serverUnavailable')}</p><p class="error">פרטי תקלה: ${errorMessage(err)}</p><button class="primary" id="retryBoot">${t(l,'tryAgain')}</button><small>${t(l,'demoModeHint')}</small></section></div>`;document.getElementById('retryBoot').onclick=()=>location.reload()}
window.addEventListener('error',e=>renderFatal(e.error||e.message));
window.addEventListener('unhandledrejection',e=>renderFatal(e.reason));
function hasStaffAccess(role){const code=sessionStorage.getItem('aiQuest.staffCode'),current=sessionStorage.getItem('aiQuest.staffRole');return !!code&&(current===role||(role==='instructor'&&current==='admin'))}
function renderAccessGate(root,role,l){const title=role==='admin'?'כניסת אדמין':'כניסת מדריך',hint=role==='admin'?'הזינו את קוד האדמין הייעודי. קוד מדריך לא פותח את מסך האדמין.':'הזינו את קוד המדריך / קוד הצ׳קפוינט של הפעילות.';root.innerHTML=`<section class="access-gate card"><h1>${title}</h1><p>המסך הזה מיועד לצוות בלבד. ${hint}</p><form id="staffLogin" class="form-grid"><label><span>קוד גישה</span><input id="staffCode" type="password" autocomplete="current-password" placeholder="קוד גישה" required autofocus></label><button class="primary">כניסה</button></form></section>`;root.querySelector('#staffLogin').onsubmit=async e=>{e.preventDefault();const code=root.querySelector('#staffCode').value.trim();if(!code)return;sessionStorage.setItem('aiQuest.staffCode',code);sessionStorage.setItem('aiQuest.staffRole',role);try{if(role==='admin')await repo.state();else{const events=repo.listActiveEvents?await repo.listActiveEvents():[];const event=events[0]||await repo.getEventByCode('GAVYAM');await repo.listTeams(event.id)}render()}catch(err){sessionStorage.removeItem('aiQuest.staffCode');sessionStorage.removeItem('aiQuest.staffRole');root.querySelector('#staffCode').value='';root.querySelector('#staffCode').focus();root.insertAdjacentHTML('beforeend','<p class="error">קוד לא תקין או שאין הרשאה למסך הזה.</p>')}}}
async function render(){try{const l=lang();setDocumentLanguage(l);const route=location.hash.replace('#','')||'student';app.className=`app-shell route-${route}`;app.innerHTML=`<nav class="tabs app-tabs route-${route}"><a href="#student" class="${route==='student'?'active':''}">${t(l,'student')}</a><a href="#instructor" class="${route==='instructor'?'active':''}">${t(l,'instructor')}</a><a href="#admin" class="${route==='admin'?'active':''}">${t(l,'admin')}</a><label class="language-switch"><span>${t(l,'language')}</span><select id="appLanguage"><option value="he" ${l==='he'?'selected':''}>${t(l,'hebrew')}</option><option value="ar" ${l==='ar'?'selected':''}>${t(l,'arabic')}</option></select></label>${route==='instructor'||route==='admin'?'<button id="staffLogout" class="ghost staff-logout">יציאה מצוות</button>':''}</nav><div id="screen"></div>`;document.getElementById('appLanguage').onchange=e=>{localStorage.setItem('aiQuest.language',e.target.value);render()};const logout=document.getElementById('staffLogout');if(logout)logout.onclick=()=>{sessionStorage.removeItem('aiQuest.staffCode');sessionStorage.removeItem('aiQuest.staffRole');render()};const root=document.getElementById('screen');if(booting){root.innerHTML='<section class="card"><h1>AI Quest</h1><p>טוען את המשחק...</p></section>';return}if(bootError||!repo){root.innerHTML=`<section class="card connection-error"><h1>${t(l,'connectionProblem')}</h1><p>${t(l,'serverUnavailable')}</p><p class="error">פרטי תקלה: ${errorMessage(bootError)}</p><button class="primary" id="retryBoot">${t(l,'tryAgain')}</button><small>${t(l,'demoModeHint')}</small></section>`;document.getElementById('retryBoot').onclick=()=>location.reload();return}if(route==='instructor'){if(!hasStaffAccess('instructor'))return renderAccessGate(root,'instructor',l);return new InstructorApp(repo,root,l).render()}if(route==='admin'){if(!hasStaffAccess('admin'))return renderAccessGate(root,'admin',l);return new AdminApp(repo,root,l).render()}return new StudentApp(repo,root,l).render()}catch(err){renderFatal(err)}}
async function boot(){booting=true;render();try{repo=await createRepository()}catch(err){bootError=err}finally{booting=false;render()}}
window.addEventListener('hashchange',render);
boot();
