export const translations = {
  he: {
    app: 'AI Quest: תעלומת המודל שהשתבש',
    student: 'תלמידים', instructor: 'מדריך', admin: 'אדמין', language: 'שפה', hebrew: 'עברית', arabic: 'العربية',
    teamName: 'שם צוות', eventCode: 'קוד אירוע', duration: 'משך פעילות', minutes: 'דקות', participants: 'מספר משתתפים', startButton: 'התחילו',
    start: 'התחילו משימה', mission: 'גלו חברות, ענו על שאלות, אספו יכולות ושפרו מודל AI.', companies: 'חברות בפארק', found: 'מצאנו את החברה', upload: 'צילום לוגו', complete: 'סיום חברה', checkpoint: 'צ׳קפוינט', requestCheckpoint: 'בקשו אישור מדריך', modelBag: 'תיק המודל', repair: 'תיקון המודל', finish: 'סיום ודירוג', score: 'ניקוד', quality: 'איכות מודל', prompt: 'פרומפט Base44', eventNotFound: 'קוד אירוע לא נמצא. נסו GAVYAM', repairGood: 'מעולה — הבחירה מחזקת את המודל.', repairTryAgain: 'בחירה מעניינת, אבל כדאי לבחור יכולת מתאימה יותר.',
    intro: 'תעלומת המודל שהשתבש — פעילות חקר דו־לשונית.', points: 'נקודות', abilities: 'יכולות', completedCompanies: 'חברות', story: 'סיפור הרקע למשחק', glossary: 'מילון קצר למושגים במשחק', glossaryHint: 'שמרנו על שפה פשוטה. אם מופיע מושג חדש במשימה — כדאי לפתוח כאן רגע ולבדוק.',
    companyPickerHint: 'מצאו לוגו בפארק וחפשו כאן לפי שם החברה. לא מציגים תחום או יכולת לפני פתיחת המשימה כדי לא לחשוף תשובות.', durationSelectionNote: 'מוצגות חברות שמתאימות לאורך המשחק שבחרתם. במשחק 135 דקות יוצגו כל החברות.', searchCompany: 'חיפוש לפי שם חברה', searchCompanyPlaceholder: 'לדוגמה: IBM / CyberArk / Wix', openCompanies: 'לא פתורות', completed: 'הושלמו', needsFix: 'צילום לא אושר', all: 'הכל', randomCompany: 'בחרו חברה אקראית', noCompanies: 'לא נמצאו חברות', noCompaniesHint: 'נסו לחפש שם אחר או לעבור לטאב אחר.', openStatus: 'לא פתורה', completedStatus: 'הושלמה', needsFixStatus: 'צריך לצלם שוב', level: 'רמה', openCompanyTask: 'פתחו משימת חברה', retakePhoto: 'צלמו שוב', noSpoiler: 'פתחו את המשימה כדי לגלות מה החברה עושה ואיזו יכולת היא מוסיפה למודל.',
    backToCompanies: 'חזרה לכל החברות', companyMission: 'משימת חברה', photoStep: 'צילום', questionsStep: 'שאלות', abilityStep: 'יכולת', photographLogo: 'צלמו את לוגו החברה', photoInstructorHint: 'הצילום יופיע למדריך לבדיקה בדשבורד.', referenceLogoOnly: 'זה סימן זיהוי בלבד. עדיין צריך למצוא ולצלם לוגו אמיתי בשטח.', realLogoRequired: 'חשוב: העלו צילום של לוגו אמיתי מהפארק — על בניין, שלט כניסה או שילוט רשמי. אין להשתמש בלוגו שמופיע באפליקציה.', choosePhoto: 'בחרו / צלמו לוגו', answerQuestions: 'ענו על השאלות', abilityYouGet: 'היכולת שתוכלו לקבל', abilityAddedHint: 'בסיום המשימה היכולות יתווספו לתיק המודל שלכם.', cancel: 'ביטול', finishedCompany: 'סיימנו חברה', companyCompleted: 'חברה הושלמה!', addedToJourney: 'נוספה למסע שלכם.', modelBagStrengthened: 'תיק המודל התחזק ביכולות:',
    progressPuzzle: 'פאזל ההתקדמות', collectedPuzzlePieces: 'אספתם', digitalPuzzlePieces: 'חלקי פאזל דיגיטליים.', returnToInstructor: 'חזרו למדריך לבדיקת התקדמות.', companiesCompleted: 'חברות הושלמו', required: 'נדרש', foodPhotoPrompt: 'צלמו / העלו לוגו של מסעדה או בית קפה בפארק', sendToInstructor: 'שלחו למדריך לאישור', uploadAndContinue: 'העלו והמשיכו', waitingInstructor: 'ממתין לאישור מדריך', puzzlePieceAfterApproval: 'אחרי אישור תקבלו חלק פאזל דיגיטלי:', checkpointSent: 'הבקשה נשלחה. גשו למדריך כדי שיאשר שאתם באמת מתקדמים במשימה.', checkpointBlocksCompanies: 'המשך חקר החברות נעול כרגע. גשו למדריך, הוא יבדוק את הסטטוס ויאשר לכם להמשיך מהדשבורד.',
    repairHint: 'בחרו יכולות שאספתם כדי לחזק נקודת חולשה במודל. ההודעה תישאר כאן עד שתסגרו אותה.', chooseAtLeastOne: 'בחרו לפחות יכולת אחת', chooseAtLeastOneText: 'כדי לתקן את המודל צריך לבחור יכולת שאספתם במשימות החברות.', modelStrengthened: 'המודל התחזק', abilityChoiceGood: 'זה יעזור למודל לתת תשובות מאוזנות יותר.', choiceNotGood: 'הבחירה לא מספיק מתאימה', choiceNotGoodText: 'נסו לבחור יכולות שמתחברות ישירות לבעיה של המודל, למשל דאטה, אבטחה, חוויית משתמש, המלצות או אתיקה.', understood: 'הבנתי', gamePoints: 'נקודות משחק', collectedAbilities: 'יכולות שנאספו', shortAnswer: 'תשובה קצרה', trueText: 'נכון', falseText: 'לא נכון',
    data: 'דאטה', security: 'אבטחה', ux: 'חוויית משתמש', recommendation: 'המלצות', ethics: 'אתיקה ופרטיות', infrastructure: 'תשתיות', communication: 'תקשורת', content: 'תוכן',
    connectionProblem: 'בעיה בחיבור לשרת', serverUnavailable: 'המשחק עובד במצב חי ודורש שרת פעיל. כרגע אי אפשר לסנכרן צוותים, תמונות וצ׳קפוינטים ולכן עצרנו כדי לא לאבד נתונים.', tryAgain: 'נסו שוב', demoModeHint: 'למצב הדגמה מקומי בלבד אפשר לפתוח עם ?demo=1.', latestUpdates: 'עדכונים אחרונים מהמדריך', finalTitle: 'המשימה הסופית: בונים מודל משופר', finalSubtitle: 'המדריך/המנהל סיים את שלב החקר. עכשיו בודקים אם אספתם מספיק יכולות כדי לפתור את בעיית הפתיחה.', finalNextStep: 'הציגו למדריך את הסיכום, הפאזל והיכולות שאספתם. אפשר גם להעתיק את הפרומפט לבניית אב־טיפוס.', finalMission: 'בדיקת מוכנות למודל המשופר', finalMissionText: 'כדי לפתוח את בניית המודל צריך להשלים לפחות 3 חברות בכל תחום: דאטה, אבטחה, חוויית משתמש, המלצות ואתיקה.', finalTrainingText: 'אימון המודל הוא תהליך חינוכי: הגדירו איזה מידע, הגנות, כללים ובקרה אנושית המודל צריך כדי לתת המלצה טובה ואחראית.', finalMissionReady: 'אתם מוכנים: אפשר להשתמש בפרומפט ולבנות מודל משופר שפותר את הבעיה שהוצגה בתחילת המשחק.', finalMissionLocked: 'עדיין חסרות חברות באחד או יותר מתחומי היכולת. הציגו למדריך מה הספקתם והיכן חסר מידע.', finalDomainsReady: 'תחומים מוכנים', strengths: 'חוזקות המודל', weaknesses: 'תחומים לשיפור', puzzleStatus: 'מצב הפאזל', instructorTitle: 'דשבורד מדריך', adminTitle: 'מערכת אדמין', modelProgressByAbility: 'התקדמות לפי תחומי יכולת:', digitalPuzzle: 'פאזל דיגיטלי', noAbilitiesYet: 'אין יכולות עדיין', repairedSoFar: 'תוקן עד עכשיו:', noWeaknessesRepaired: 'עדיין לא תוקנו חולשות במודל', repairModelButton: 'תקנו את המודל עם היכולות שבחרנו'
  },
  ar: {
    app: 'AI Quest: لغز النموذج الذي تعطّل',
    student: 'الطلاب', instructor: 'المرشد', admin: 'الإدارة', language: 'اللغة', hebrew: 'עברית', arabic: 'العربية',
    teamName: 'اسم الفريق', eventCode: 'رمز الفعالية', duration: 'مدة النشاط', minutes: 'دقائق', participants: 'عدد المشاركين', startButton: 'ابدأوا',
    start: 'ابدأوا المهمة', mission: 'اكتشفوا شركات، أجيبوا عن أسئلة، اجمعوا قدرات وحسّنوا نموذج AI.', companies: 'الشركات في المجمع', found: 'وجدنا الشركة', upload: 'صورة الشعار', complete: 'إنهاء الشركة', checkpoint: 'نقطة تحقق', requestCheckpoint: 'اطلبوا موافقة المرشد', modelBag: 'ملف النموذج', repair: 'إصلاح النموذج', finish: 'النهاية والتقييم', score: 'النقاط', quality: 'جودة النموذج', prompt: 'موجه Base44', eventNotFound: 'رمز الفعالية غير موجود. جرّبوا GAVYAM', repairGood: 'رائع — الاختيار يقوي النموذج.', repairTryAgain: 'اختيار مثير، لكن اختاروا قدرة أنسب.',
    intro: 'لغز النموذج الذي تعطّل — نشاط بحث ثنائي اللغة.', points: 'نقاط', abilities: 'قدرات', completedCompanies: 'شركات', story: 'قصة اللعبة', glossary: 'قاموس مصطلحات قصير', glossaryHint: 'استخدمنا لغة بسيطة. إذا ظهر مصطلح جديد في المهمة، افتحوا القاموس للحظة.',
    companyPickerHint: 'ابحثوا عن شعار في المجمع وابحثوا هنا حسب اسم الشركة. لا نكشف المجال أو القدرة قبل فتح المهمة كي لا نعطي الإجابات مسبقًا.', durationSelectionNote: 'تظهر هنا شركات مناسبة لمدة اللعبة التي اخترتموها. في لعبة 135 دقيقة تظهر كل الشركات.', searchCompany: 'بحث حسب اسم الشركة', searchCompanyPlaceholder: 'مثل: IBM / CyberArk / Wix', openCompanies: 'غير محلولة', completed: 'مكتملة', needsFix: 'الصورة لم تُقبل', all: 'الكل', randomCompany: 'اختاروا شركة عشوائية', noCompanies: 'لم يتم العثور على شركات', noCompaniesHint: 'جرّبوا اسمًا آخر أو انتقلوا إلى تبويب آخر.', openStatus: 'غير محلولة', completedStatus: 'مكتملة', needsFixStatus: 'يجب التصوير مرة أخرى', level: 'المستوى', openCompanyTask: 'افتحوا مهمة الشركة', retakePhoto: 'صوّروا مرة أخرى', noSpoiler: 'افتحوا المهمة لتكتشفوا ماذا تفعل الشركة وأي قدرة تضيفها للنموذج.',
    backToCompanies: 'العودة إلى كل الشركات', companyMission: 'مهمة شركة', photoStep: 'تصوير', questionsStep: 'أسئلة', abilityStep: 'قدرة', photographLogo: 'صوّروا شعار الشركة', photoInstructorHint: 'ستظهر الصورة للمرشد للمراجعة في لوحة المتابعة.', referenceLogoOnly: 'هذه علامة مساعدة فقط. يجب العثور على شعار حقيقي وتصويره في المكان.', realLogoRequired: 'مهم: ارفعوا صورة لشعار حقيقي من المجمع — على مبنى، لافتة مدخل أو لافتة رسمية. لا تستخدموا الشعار الظاهر في التطبيق.', choosePhoto: 'اختاروا / صوّروا شعارًا', answerQuestions: 'أجيبوا عن الأسئلة', abilityYouGet: 'القدرة التي ستحصلون عليها', abilityAddedHint: 'عند إنهاء المهمة ستُضاف القدرات إلى ملف النموذج.', cancel: 'إلغاء', finishedCompany: 'أنهينا الشركة', companyCompleted: 'تم إنهاء الشركة!', addedToJourney: 'أُضيفت إلى رحلتكم.', modelBagStrengthened: 'تعزّز ملف النموذج بالقدرات:',
    progressPuzzle: 'أحجية التقدم', collectedPuzzlePieces: 'جمعتم', digitalPuzzlePieces: 'قطع أحجية رقمية.', returnToInstructor: 'عودوا إلى المرشد لفحص التقدم.', companiesCompleted: 'شركات مكتملة', required: 'المطلوب', foodPhotoPrompt: 'صوّروا / ارفعوا شعار مطعم أو مقهى في المجمع', sendToInstructor: 'أرسلوا للمرشد للموافقة', uploadAndContinue: 'ارفعوا وتابعوا', waitingInstructor: 'بانتظار موافقة المرشد', puzzlePieceAfterApproval: 'بعد الموافقة ستحصلون على قطعة أحجية رقمية:', checkpointSent: 'تم إرسال الطلب. توجّهوا إلى المرشد ليؤكد أنكم تتقدمون فعلًا في المهمة.', checkpointBlocksCompanies: 'استكشاف الشركات مقفل الآن. توجّهوا إلى المرشد، يفحص حالتكم ويوافق من لوحة التحكم كي تتابعوا.',
    repairHint: 'اختاروا قدرات جمعتموها كي تقوّوا نقطة ضعف في النموذج. ستبقى الرسالة هنا حتى تغلقوها.', chooseAtLeastOne: 'اختاروا قدرة واحدة على الأقل', chooseAtLeastOneText: 'كي تصلحوا النموذج يجب اختيار قدرة جمعتموها في مهام الشركات.', modelStrengthened: 'النموذج أصبح أقوى', abilityChoiceGood: 'هذا سيساعد النموذج على إعطاء إجابات أكثر توازنًا.', choiceNotGood: 'الاختيار غير مناسب كفاية', choiceNotGoodText: 'حاولوا اختيار قدرات مرتبطة مباشرة بمشكلة النموذج، مثل البيانات، الأمان، تجربة المستخدم، التوصيات أو الأخلاقيات.', understood: 'فهمت', gamePoints: 'نقاط اللعبة', collectedAbilities: 'قدرات جُمعت', shortAnswer: 'إجابة قصيرة', trueText: 'صحيح', falseText: 'غير صحيح',
    data: 'بيانات', security: 'أمان', ux: 'تجربة المستخدم', recommendation: 'توصيات', ethics: 'أخلاقيات وخصوصية', infrastructure: 'بنية تحتية', communication: 'اتصال', content: 'محتوى',
    connectionProblem: 'مشكلة في الاتصال بالخادم', serverUnavailable: 'اللعبة تعمل كنشاط حي وتحتاج إلى خادم فعّال. لا يمكن الآن مزامنة الفرق والصور ونقاط التحقق، لذلك أوقفنا اللعبة كي لا تضيع البيانات.', tryAgain: 'حاولوا مرة أخرى', demoModeHint: 'لوضع تجريبي محلي فقط افتحوا الرابط مع ?demo=1.', latestUpdates: 'آخر تحديثات المرشد', finalTitle: 'المهمة النهائية: نبني نموذجًا محسّنًا', finalSubtitle: 'أنهى المرشد/المدير مرحلة البحث. الآن نفحص هل جمعتم قدرات كافية لحل مشكلة البداية.', finalNextStep: 'اعرضوا على المرشد الملخص والأحجية والقدرات التي جمعتموها. يمكنكم أيضًا نسخ الموجه لبناء نموذج أولي.', finalMission: 'فحص الجاهزية للنموذج المحسّن', finalMissionText: 'لفتح بناء النموذج يجب إنهاء 3 شركات على الأقل في كل مجال: البيانات، الأمان، تجربة المستخدم، التوصيات والأخلاقيات.', finalTrainingText: 'تدريب النموذج هو عملية تعليمية: حدّدوا ما هي المعلومات والحمايات والقواعد والرقابة البشرية التي يحتاجها النموذج كي يعطي توصية جيدة ومسؤولة.', finalMissionReady: 'أنتم جاهزون: يمكن استخدام الموجه وبناء نموذج محسّن يحل المشكلة التي ظهرت في بداية اللعبة.', finalMissionLocked: 'ما زالت تنقص شركات في مجال قدرة واحد أو أكثر. اعرضوا للمرشد ما أنجزتم وأين ينقصكم معلومات.', finalDomainsReady: 'مجالات جاهزة', strengths: 'نقاط قوة النموذج', weaknesses: 'مجالات للتحسين', puzzleStatus: 'حالة الأحجية', instructorTitle: 'لوحة المرشد', adminTitle: 'لوحة الإدارة', modelProgressByAbility: 'التقدم حسب مجالات القدرة:', digitalPuzzle: 'الأحجية الرقمية', noAbilitiesYet: 'لا توجد قدرات بعد', repairedSoFar: 'تم إصلاحه حتى الآن:', noWeaknessesRepaired: 'لم يتم إصلاح نقاط ضعف في النموذج بعد', repairModelButton: 'أصلحوا النموذج بالقدرات التي اخترتموها'
  }
};
export const t = (l, k) => translations[l]?.[k] || translations.he[k] || k;
